/**
 * Gold & Silver Arbitrage Platform - Core Types
 */

// Asset types supported by the platform
export type AssetType = 'GOLD' | 'SILVER';

// Data source identifiers
export type DataSource = 'BINANCE' | 'TRADE_REPUBLIC' | 'EXCEL' | 'MANUAL';

// Market state indicators
export type MarketState = 'OPEN' | 'CLOSED' | 'PRE_MARKET' | 'AFTER_HOURS';

// Trading signal types
export type SignalType = 'BUY' | 'SELL' | 'WATCH' | 'ALERT';

// Signal confidence levels
export type ConfidenceLevel = 'HIGH' | 'MEDIUM' | 'LOW';

// Connection status for real-time data
export type ConnectionStatus = 'CONNECTED' | 'CONNECTING' | 'DISCONNECTED' | 'ERROR';

/**
 * Normalized price record from any data source
 */
export interface NormalizedPrice {
  source: DataSource;
  assetType: AssetType;
  symbol: string;
  displayName: string;
  price: number;
  bid?: number;
  ask?: number;
  change24h?: number;
  changePercent24h?: number;
  volume24h?: number;
  currency: 'USD' | 'EUR';
  timestamp: string;
  exchange: string;
  instrumentType: 'SPOT' | 'ETC' | 'ETF' | 'TOKEN';
  referenceUnit: 'OZ' | 'GRAM' | 'UNIT';
  marketState: MarketState;
  isStale: boolean;
  staleSince?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Trade Republic instrument definition
 */
export interface TRInstrument {
  isin: string;
  name: string;
  shortName: string;
  assetType: AssetType;
  currency: 'EUR' | 'USD';
  exchange: string;
  gramPerUnit?: number; // For gold/silver ETCs: grams of metal per unit
  expenseRatio?: number; // Annual expense ratio
  issuer: string;
  active: boolean;
}

/**
 * Binance reference instrument
 */
export interface BinanceInstrument {
  symbol: string;
  displayName: string;
  assetType: AssetType;
  baseAsset: string;
  quoteAsset: string;
  pricePrecision: number;
  quantityPrecision: number;
  active: boolean;
}

/**
 * Spread calculation result
 */
export interface SpreadResult {
  id: string;
  assetType: AssetType;
  trInstrument: TRInstrument;
  binanceSymbol: string;
  trPrice: number;
  trBid?: number;
  trAsk?: number;
  binancePrice: number;
  binanceBid?: number;
  binanceAsk?: number;
  spreadAbs: number; // Absolute spread in currency
  spreadPct: number; // Percentage spread
  spreadBps: number; // Spread in basis points
  zScore: number; // Standard deviations from mean
  historicalMean: number;
  historicalStdDev: number;
  confidence: ConfidenceLevel;
  currency: 'EUR' | 'USD';
  fxRate?: number; // EUR/USD rate if applicable
  timestamp: string;
  marketHoursComparable: boolean;
  trMarketState: MarketState;
  binanceMarketState: MarketState;
  isStale: boolean;
  netEdgeAfterFees?: number; // Spread minus estimated trading costs
}

/**
 * Trading signal generated by the signal engine
 */
export interface TradingSignal {
  id: string;
  assetType: AssetType;
  instrumentId: string;
  instrumentName: string;
  signalType: SignalType;
  spreadPct: number;
  spreadBps: number;
  zScore: number;
  confidence: ConfidenceLevel;
  rationale: string;
  suggestedAction?: string;
  priceAtSignal: number;
  targetPrice?: number;
  stopLoss?: number;
  timestamp: string;
  expiresAt?: string;
  status: 'NEW' | 'ACTIVE' | 'EXPIRED' | 'ACKNOWLEDGED' | 'TRIGGERED';
  priority: 'CRITICAL' | 'HIGH' | 'NORMAL' | 'LOW';
  metadata?: Record<string, unknown>;
}

/**
 * Historical spread data point
 */
export interface SpreadHistoryPoint {
  timestamp: string;
  spreadPct: number;
  spreadBps: number;
  trPrice: number;
  binancePrice: number;
  volume?: number;
}

/**
 * Weekly gap analysis
 */
export interface WeeklyGap {
  weekStart: string;
  weekEnd: string;
  fridayClose: number;
  mondayOpen: number;
  gapAbs: number;
  gapPct: number;
  filled: boolean;
  fillTime?: string;
  fillPct?: number;
}

/**
 * Alert threshold configuration
 */
export interface AlertThreshold {
  id: string;
  assetType: AssetType;
  instrumentId?: string; // Optional: specific instrument, null = all
  spreadPctBuy: number; // e.g., -1.0 (TR cheaper)
  spreadPctSell: number; // e.g., +1.0 (TR expensive)
  zScoreThreshold: number; // e.g., 2.0
  enabled: boolean;
  notifyInApp: boolean;
  notifyEmail?: boolean;
  notifyTelegram?: boolean;
  notifyDiscord?: boolean;
  cooldownMinutes: number; // Minimum time between alerts
  createdAt: string;
  updatedAt: string;
}

/**
 * User preferences for the platform
 */
export interface UserPreferences {
  defaultAssetType: AssetType;
  refreshIntervalMs: number;
  showStalePrices: boolean;
  staleThresholdMs: number;
  displayCurrency: 'EUR' | 'USD';
  timezone: string;
  soundAlerts: boolean;
  compactMode: boolean;
  favoriteInstruments: string[];
  alertThresholds: AlertThreshold[];
}

/**
 * Platform state snapshot
 */
export interface PlatformState {
  binanceConnected: ConnectionStatus;
  trConnected: ConnectionStatus;
  lastBinanceUpdate: string;
  lastTRUpdate: string;
  activeSpreads: SpreadResult[];
  activeSignals: TradingSignal[];
  goldPrice: NormalizedPrice | null;
  silverPrice: NormalizedPrice | null;
  eurUsdRate: number;
  errors: PlatformError[];
}

/**
 * Platform error
 */
export interface PlatformError {
  id: string;
  code: string;
  message: string;
  source: DataSource | 'SYSTEM';
  severity: 'ERROR' | 'WARNING' | 'INFO';
  timestamp: string;
  resolved: boolean;
  resolvedAt?: string;
}

/**
 * Excel export configuration
 */
export interface ExcelExportConfig {
  includeGold: boolean;
  includeSilver: boolean;
  includeSpreads: boolean;
  includeSignals: boolean;
  includeHistory: boolean;
  historyDays: number;
  format: 'CSV' | 'XLSX';
  autoExport: boolean;
  autoExportIntervalMinutes: number;
}

/**
 * Market hours configuration
 */
export interface MarketHours {
  exchange: string;
  timezone: string;
  regularOpen: string; // HH:mm format
  regularClose: string;
  preMarketOpen?: string;
  afterHoursClose?: string;
  tradingDays: number[]; // 0 = Sunday, 1 = Monday, etc.
  holidays: string[]; // ISO date strings
}

/**
 * Arbitrage opportunity summary
 */
export interface ArbitrageOpportunity {
  id: string;
  assetType: AssetType;
  direction: 'BUY_TR_SELL_BINANCE' | 'BUY_BINANCE_SELL_TR';
  trInstrument: TRInstrument;
  binanceSymbol: string;
  entrySpreadPct: number;
  currentSpreadPct: number;
  potentialProfitPct: number;
  potentialProfitAbs: number;
  estimatedFees: number;
  netProfitPct: number;
  confidence: ConfidenceLevel;
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH';
  timestamp: string;
  expiresAt: string;
  status: 'OPEN' | 'CLOSED' | 'EXPIRED';
}

/**
 * Price tick for real-time updates
 */
export interface PriceTick {
  source: DataSource;
  symbol: string;
  price: number;
  bid?: number;
  ask?: number;
  volume?: number;
  timestamp: string;
}

/**
 * Candle/OHLCV data
 */
export interface Candle {
  openTime: string;
  closeTime: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  quoteVolume?: number;
  trades?: number;
}

/**
 * Order book snapshot
 */
export interface OrderBookLevel {
  price: number;
  quantity: number;
}

export interface OrderBook {
  symbol: string;
  bids: OrderBookLevel[];
  asks: OrderBookLevel[];
  timestamp: string;
}
